#index:
#    path: /
#    controller: App\Controller\DefaultController::index
health-check_get:
  path: /health-check
  controller:  App\Controller\HealthCheckGetController
  methods: [GET]

beer-by-food_get:
  path: /beer-by-food
  controller:  App\Controller\BeerByFoodGetController
  methods: [GET]